backend = "glx";
corner-radius = 12;
rounded-corners-exclude = [
    "class_g = 'polybar'",
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
corner-radius-rules = [
    "0:fullscreen"
];

vsync = true;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -6;
shadow-offset-y = -6;
shadow-opacity = 0.35;

shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@"
];

fading = true;
fade-in-step = 0.07;
fade-out-step = 0.07;
